### ISSUE TITLE
Getting groups user is in

### ISSUE THREAD

**Issue by ghost** [SmItH197/SteamAuthentication#75]
I am able to use "primaryclanid" fine to retrieve the users primary group.
But how could i take this script further to retreive all the group ID the user is in?

I would use this to check if they have joined my steam group, by comparing the list of returned group IDs.

Thanks alot.

**Comment by BlackCetha** [comment]
Unfortunately that is a bit more complicated because you cannot directly get the user's group list.

Instead you need to call the memberlist of your group and check if the user is in it.
For example http://steamcommunity.com/gid/103582791429521412/memberslistxml/?xml=1 (for VALVE group). Replace the number after /gid/ with your group's unique ID. It returns XML so you might have to dig into that a bit.

**Comment by wortel538** [comment]
Maybe a stupid way to do, but you can try to load the webpages-sourcecode
of the users group list to string and Search into that with Contains the
group of your need? Sorry for grammarfaults, I'm typing this on phone.

**Comment by BlackCetha** [comment]
You could, but its a violation of valve's TOS, slow and dirty.

**Comment by wortel538** [comment]
Oh, OK, nvm then :x
