### ISSUE TITLE
STEAM AUTH ERROR problems in userinfo.php & settings.php

### ISSUE THREAD

**Issue by ANK-RULZZ** [SmItH197/SteamAuthentication#85]
Warning: include(/home/u646521552/public_html/steamauth/settings.php): failed to open stream: No such file or directory in /home/u646521552/public_html/html/steamauth/userInfo.php on line 2

Warning: include(): Failed opening '/home/u646521552/public_html/steamauth/settings.php' for inclusion (include_path='.:/opt/php-5.5/pear') in /home/u646521552/public_html/html/steamauth/userInfo.php on line 2

Warning: file_get_contents(http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=&steamids=76561198067950294): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden in /home/u646521552/public_html/html/steamauth/userInfo.php on line 4

please help to fix this i got this while i was building my csgo site how to fix it thank you

**Comment by BlackCetha** [comment]
The error message is pretty clear: Your PHP is not able to access the neccessary files. This is probably caused by the user www-data not having previledges to read from /steamauth/. If you have the possibility of changing the file permissions in your hosting panel, do that. Otherwise you may have to contact your hosters suppport.

The file_get_contents error is caused by the missing key parameter in your config. You can generate your key at http://steamcommunity.com/dev/apikey.
