### ISSUE TITLE
WordPress integration

### ISSUE THREAD

**Issue by Boeng06** [SmItH197/SteamAuthentication#95]
I use wordpress to my page how can I put SteamAuthentication in?

**Comment by SmItH197** [comment]
I have absolutely no idea, I haven't used WordPress

**Comment by Boeng06** [comment]
I use filezilla to put plugins in, can i do that too with SteamAuthentication? :)

**Comment by SmItH197** [comment]
Filezilla is an ftp client right? You can upload it using filezilla, but its not in the WordPress plugin structure. 

What about the following: https://wordpress.org/plugins/wordpress-social-login/

That's a WordPress plugin that has steam login support.

**Comment by Boeng06** [comment]
I have just talk to a support, they say i can use FTP to put plugins into wordpress.:)
 it is as good as yours? :)

**Comment by SmItH197** [comment]
Mine is not built for WordPress, I would recommend the link above as mine would take a lot of modifications to integrate with WordPress.

**Comment by Boeng06** [comment]
Do you have time too teamViewer, because i really need you help :)

**Comment by SmItH197** [comment]
Sure, email me at smithben238[at]gmail.com

**Comment by Boeng06** [comment]
I can't send my teamViewer options to you'r email, i can't find it? :)

**Comment by SmItH197** [comment]
Try again now

**Comment by Boeng06** [comment]
send something to my email :)

**Comment by Boeng06** [comment]
lukasboeng@gmail.com

**Comment by SmItH197** [comment]
Sent you an email

**Comment by Gummibeer** [comment]
Some keywords:

Use the wordpress hooks & actions to modify the way the login works, the Main Problem would be the missing email, for this you can create a custom view to Request the email from the User.

So a Plugin is the right way - but it's mit done by including this package. You have to create the communications between this package and wordpress by your own.

**Comment by bman46** [comment]
I have never used wordpress before, but i found this plugin that may help put it would mean that you would have to modify the code a bit. https://wordpress.org/plugins/insert-php/faq/ But i would probably recommend using SmItH197's plugin because it was build for wordpress and i don't know if the php solution will work because it requires there to be files with only php on it.

> SmItH197 commented on Jan 9
Filezilla is an ftp client right? You can upload it using filezilla, but its not in the WordPress plugin structure.

What about the following: https://wordpress.org/plugins/wordpress-social-login/

That's a WordPress plugin that has steam login support.<
